### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by xsIceman** [ToddThomson/MsAGL#1]
what license do you plan to use on the project?

**Comment by ToddThomson** [comment]
@xsIceman The original license was MIT and I will continue to use it. I will be updating the repo this week. 

The main area that I will be focusing on for my changes will be the Drawing and GraphControl. These will be brought up to date with UWP guidelines for design and UX. The core MsAGL library has alot of baggage and will be worked on, but it is not my top priority.

**Comment by ToddThomson** [comment]
Related: Add readme

**Comment by ToddThomson** [comment]
@xsIceman LICENSE and Readme.md add. Thank-you for your input.

**Comment by xsIceman** [comment]
How much work would it be to change the MsAGL library from UWP to .NET standard?

**Comment by ToddThomson** [comment]
@xsIceman The current version of Windows 10 UWP is .netstandard 1.6.  The upcoming Fall Update will be .netstandard 2.0.

I've already updated the  original MSAGL core library implementation to the current version of UWP. It should be mostly OK now, but I really haven't tested much of it. The GraphViewer and Drawing libraries are not really in good shape and this is currently the area I am investing my time. I should have a full graph editor app by next week.

UWP is quite different from WPF and there are a lot of changes required. The other issue is that the original implementation of the WPF GraphViewer is incomplete compared to the GDI version. It shouldn't take me too long to get things working though!
